name: rolling Binary Build RHEL
on:
  pull_request:
    branches:
      - rolling
  push:
    #branches:
      #- rolling

jobs:
  rolling_binary_rhel:
    name: rolling binary build
    runs-on: ubuntu-latest
    container: ghcr.io/ros-controls/ros:rolling-rhel
    env:
      ROS_DISTRO: rolling
    steps:
      - uses: actions/checkout@v3
        with:
          path: src/ur_ros2_driver
      # As long as industrial-ci doesn't support using anything different than ubuntu, we'll just
      # build it manually.
      - run: |
          rosdep update
          rosdep install -y --from-path --ignore-src src/ur_ros2_driver
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          colcon build
