name: Rolling Binary Build
on:
  workflow_dispatch:
  push:
    branches:
      - debug_tests
  schedule:
    # Run every hour to debug flakiness in tests
    - cron: '35 * * * *'

jobs:
  rolling_binary:
    name: rolling binary build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [rolling]
        ROS_REPO: [main]
    env:
      UPSTREAM_WORKSPACE: Universal_Robots_ROS2_Driver-not-released.${{ matrix.ROS_DISTRO }}.repos
      DOCKER_RUN_OPTS: '-v /var/run/docker.sock:/var/run/docker.sock --network ursim_net'
    steps:
      - uses: actions/checkout@v1
      - run: docker network create --subnet=192.168.56.0/24 ursim_net
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          ROS_REPO: ${{ matrix.ROS_REPO }}
          CMAKE_ARGS: -DUR_ROBOT_DRIVER_BUILD_INTEGRATION_TESTS=ON
